name: Spleeter Envs
run-name: ${{ github.ref_name}} Spleeter Envs

on:
    release:
        types: [published]

jobs:
    create-env:
        strategy:
            fail-fast: false
            matrix:
                os: ["windows-latest"]
      
        name: Create Env (${{ matrix.os }})
        runs-on: ${{ matrix.os }}
        steps:
          - uses: conda-incubator/setup-miniconda@v3
            with:
                auto-update-conda: true
                activate-environment: "spleeter-env"
                python-version: 3.8
          - name: Conda Install
            run: |
                conda install conda-pack
                conda create -n spleeter-env -c conda-forge ffmpeg
                conda activate spleeter-env
                pip install spleeter==2.*
          - name: Conda Pack
            run: conda pack --output spleeter-env-${{ matrix.os }}.zip
          - name: Retrieve Release
            id: retrieve_release
            uses: octokit/request-action@v2.x
            env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            with:
                route: GET /repos/${{ github.repository }}/releases/tags/${{ github.ref_name }}
      
          - name: Upload Environment
            id: upload_environment
            run: |
              curl -L \
              -X POST \
              -H "Accept: application/vnd.github+json" \
              -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
              -H "X-GitHub-Api-Version: 2022-11-28" \
              -H "Content-Type: application/octet-stream" \
              "https://uploads.github.com/repos/${{ github.repository }}/releases/${{ fromJson(steps.retrieve_release.outputs.data).id }}/assets?name=spleeter-env-${{ matrix.os }}.zip" \
                --data-binary "@./spleeter-env-${{ matrix.os }}.zip"